# fly.toml app configuration file generated for drizzle-run on 2024-06-29T17:47:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drizzle-run'
primary_region = 'cdg'
swap_size_mb = 512

[deploy]
strategy = "bluegreen"

[env]
NODE_ENV = "production"
PORT = "3000"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[http_service.concurrency]
type = "requests"
soft_limit = 125
hard_limit = 150

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/healthcheck"

[[vm]]
memory = '1024mb'
cpu_kind = 'shared'
cpus = 1
